version: "3.9"

services:
  sbs:
    build: "./"
    restart: always
    env_file:
      - ../.SBS.env
    environment:
      - HTTPPORT=${DOCKER_PORT}
      - MONGOMongoPORT=${DOCKER_MONGOMongoPORT}
      - MONGOMongoHOST=mongodb
      - MONGOMongoUSER=${DOCKER_MOGNOMongoUSERNAME}
      - MONGOMongoPASSWD=${DOCKER_MOGNOMongoPASSWORD}
      - MONGOMongoDATABASE=${DOCKER_DATABASE}
    volumes:
      # config for the cashboard if you want to edit that copy to a other path and mount it to here.
      - ./mount/files:/mount/
      - ./mount/users:/build/images/user/
    external_links:
      - mongodb:mongodb
    networks:
      - databases_default

networks:
  databases_default:
    external: true